// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: robcord/bridge/v1/bridge.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventStreamRequest is sent by the Workspace on the EventStream.
type EventStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventStreamRequest_SessionOpenAck
	//	*EventStreamRequest_SessionFrame
	//	*EventStreamRequest_SessionClose
	//	*EventStreamRequest_Pong
	//	*EventStreamRequest_Heartbeat
	//	*EventStreamRequest_DispatchResponse
	//	*EventStreamRequest_TokenRotationAck
	//	*EventStreamRequest_CertRenewalAck
	//	*EventStreamRequest_WorkspaceBroadcast
	Payload       isEventStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *EventStreamRequest) GetPayload() isEventStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventStreamRequest) GetSessionOpenAck() *SessionOpenAck {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_SessionOpenAck); ok {
			return x.SessionOpenAck
		}
	}
	return nil
}

func (x *EventStreamRequest) GetSessionFrame() *SessionFrame {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_SessionFrame); ok {
			return x.SessionFrame
		}
	}
	return nil
}

func (x *EventStreamRequest) GetSessionClose() *SessionClose {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_SessionClose); ok {
			return x.SessionClose
		}
	}
	return nil
}

func (x *EventStreamRequest) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *EventStreamRequest) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *EventStreamRequest) GetDispatchResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_DispatchResponse); ok {
			return x.DispatchResponse
		}
	}
	return nil
}

func (x *EventStreamRequest) GetTokenRotationAck() *TokenRotationAck {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_TokenRotationAck); ok {
			return x.TokenRotationAck
		}
	}
	return nil
}

func (x *EventStreamRequest) GetCertRenewalAck() *CertRenewalAck {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_CertRenewalAck); ok {
			return x.CertRenewalAck
		}
	}
	return nil
}

func (x *EventStreamRequest) GetWorkspaceBroadcast() *WorkspaceBroadcast {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamRequest_WorkspaceBroadcast); ok {
			return x.WorkspaceBroadcast
		}
	}
	return nil
}

type isEventStreamRequest_Payload interface {
	isEventStreamRequest_Payload()
}

type EventStreamRequest_SessionOpenAck struct {
	// Session management (WS Bridge replacement)
	SessionOpenAck *SessionOpenAck `protobuf:"bytes,1,opt,name=session_open_ack,json=sessionOpenAck,proto3,oneof"`
}

type EventStreamRequest_SessionFrame struct {
	SessionFrame *SessionFrame `protobuf:"bytes,2,opt,name=session_frame,json=sessionFrame,proto3,oneof"`
}

type EventStreamRequest_SessionClose struct {
	SessionClose *SessionClose `protobuf:"bytes,3,opt,name=session_close,json=sessionClose,proto3,oneof"`
}

type EventStreamRequest_Pong struct {
	// Keepalive
	Pong *Pong `protobuf:"bytes,10,opt,name=pong,proto3,oneof"`
}

type EventStreamRequest_Heartbeat struct {
	// Heartbeat (inline on stream, alternative to unary RPC)
	Heartbeat *HeartbeatRequest `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type EventStreamRequest_DispatchResponse struct {
	// Dispatch response (Workspace executed the HTTP request, here's the result)
	DispatchResponse *HttpResponse `protobuf:"bytes,12,opt,name=dispatch_response,json=dispatchResponse,proto3,oneof"`
}

type EventStreamRequest_TokenRotationAck struct {
	// Token rotation acknowledgement (response to TokenRotationRequestedEvent)
	TokenRotationAck *TokenRotationAck `protobuf:"bytes,13,opt,name=token_rotation_ack,json=tokenRotationAck,proto3,oneof"`
}

type EventStreamRequest_CertRenewalAck struct {
	// Cert renewal acknowledgement (response to CertRenewalEvent)
	CertRenewalAck *CertRenewalAck `protobuf:"bytes,14,opt,name=cert_renewal_ack,json=certRenewalAck,proto3,oneof"`
}

type EventStreamRequest_WorkspaceBroadcast struct {
	// Workspace broadcast: forward a WS hub event to all browser sessions.
	// Used for message_created, channel_created, member_joined, etc.
	WorkspaceBroadcast *WorkspaceBroadcast `protobuf:"bytes,15,opt,name=workspace_broadcast,json=workspaceBroadcast,proto3,oneof"`
}

func (*EventStreamRequest_SessionOpenAck) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_SessionFrame) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_SessionClose) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_Pong) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_Heartbeat) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_DispatchResponse) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_TokenRotationAck) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_CertRenewalAck) isEventStreamRequest_Payload() {}

func (*EventStreamRequest_WorkspaceBroadcast) isEventStreamRequest_Payload() {}

// EventStreamResponse is sent by the Zentrale on the EventStream.
type EventStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventStreamResponse_SessionOpen
	//	*EventStreamResponse_SessionFrame
	//	*EventStreamResponse_SessionClose
	//	*EventStreamResponse_BridgeEvent
	//	*EventStreamResponse_Ping
	//	*EventStreamResponse_DispatchRequest
	//	*EventStreamResponse_HeartbeatResponse
	Payload       isEventStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamResponse) Reset() {
	*x = EventStreamResponse{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamResponse) ProtoMessage() {}

func (x *EventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamResponse.ProtoReflect.Descriptor instead.
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *EventStreamResponse) GetPayload() isEventStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventStreamResponse) GetSessionOpen() *SessionOpen {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_SessionOpen); ok {
			return x.SessionOpen
		}
	}
	return nil
}

func (x *EventStreamResponse) GetSessionFrame() *SessionFrame {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_SessionFrame); ok {
			return x.SessionFrame
		}
	}
	return nil
}

func (x *EventStreamResponse) GetSessionClose() *SessionClose {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_SessionClose); ok {
			return x.SessionClose
		}
	}
	return nil
}

func (x *EventStreamResponse) GetBridgeEvent() *BridgeEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_BridgeEvent); ok {
			return x.BridgeEvent
		}
	}
	return nil
}

func (x *EventStreamResponse) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *EventStreamResponse) GetDispatchRequest() *DispatchRequest {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_DispatchRequest); ok {
			return x.DispatchRequest
		}
	}
	return nil
}

func (x *EventStreamResponse) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*EventStreamResponse_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

type isEventStreamResponse_Payload interface {
	isEventStreamResponse_Payload()
}

type EventStreamResponse_SessionOpen struct {
	// Session management
	SessionOpen *SessionOpen `protobuf:"bytes,1,opt,name=session_open,json=sessionOpen,proto3,oneof"`
}

type EventStreamResponse_SessionFrame struct {
	SessionFrame *SessionFrame `protobuf:"bytes,2,opt,name=session_frame,json=sessionFrame,proto3,oneof"`
}

type EventStreamResponse_SessionClose struct {
	SessionClose *SessionClose `protobuf:"bytes,3,opt,name=session_close,json=sessionClose,proto3,oneof"`
}

type EventStreamResponse_BridgeEvent struct {
	// Bridge events (fire-and-forget, no ack needed)
	BridgeEvent *BridgeEvent `protobuf:"bytes,5,opt,name=bridge_event,json=bridgeEvent,proto3,oneof"`
}

type EventStreamResponse_Ping struct {
	// Keepalive
	Ping *Ping `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type EventStreamResponse_DispatchRequest struct {
	// Dispatch (HTTP proxy request via stream)
	DispatchRequest *DispatchRequest `protobuf:"bytes,11,opt,name=dispatch_request,json=dispatchRequest,proto3,oneof"`
}

type EventStreamResponse_HeartbeatResponse struct {
	// Heartbeat response (inline)
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,12,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

func (*EventStreamResponse_SessionOpen) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_SessionFrame) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_SessionClose) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_BridgeEvent) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_Ping) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_DispatchRequest) isEventStreamResponse_Payload() {}

func (*EventStreamResponse_HeartbeatResponse) isEventStreamResponse_Payload() {}

// SessionOpen is sent by Zentrale to create a virtual browser WS session on the Workspace.
type SessionOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpen) Reset() {
	*x = SessionOpen{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpen) ProtoMessage() {}

func (x *SessionOpen) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpen.ProtoReflect.Descriptor instead.
func (*SessionOpen) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *SessionOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOpen) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionOpen) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// SessionOpenAck is sent by Workspace to confirm session creation.
type SessionOpenAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpenAck) Reset() {
	*x = SessionOpenAck{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpenAck) ProtoMessage() {}

func (x *SessionOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpenAck.ProtoReflect.Descriptor instead.
func (*SessionOpenAck) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *SessionOpenAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOpenAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionOpenAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SessionFrame carries a single WebSocket frame between browser and Workspace.
type SessionFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsText        bool                   `protobuf:"varint,3,opt,name=is_text,json=isText,proto3" json:"is_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFrame) Reset() {
	*x = SessionFrame{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFrame) ProtoMessage() {}

func (x *SessionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFrame.ProtoReflect.Descriptor instead.
func (*SessionFrame) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *SessionFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SessionFrame) GetIsText() bool {
	if x != nil {
		return x.IsText
	}
	return false
}

// SessionClose terminates a virtual browser WS session.
type SessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *SessionClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionClose) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SessionClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WorkspaceBroadcast carries a WS hub event from the Workspace to all browser
// sessions connected via the Zentrale. The payload is the raw JSON event frame
// (e.g. {"type":"message_created","payload":{...}}).
type WorkspaceBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsText        bool                   `protobuf:"varint,2,opt,name=is_text,json=isText,proto3" json:"is_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceBroadcast) Reset() {
	*x = WorkspaceBroadcast{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBroadcast) ProtoMessage() {}

func (x *WorkspaceBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBroadcast.ProtoReflect.Descriptor instead.
func (*WorkspaceBroadcast) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *WorkspaceBroadcast) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WorkspaceBroadcast) GetIsText() bool {
	if x != nil {
		return x.IsText
	}
	return false
}

// BridgeEvent carries Zentrale-to-Workspace notifications.
type BridgeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*BridgeEvent_UserBanned
	//	*BridgeEvent_UserUnbanned
	//	*BridgeEvent_ConnectionModeChanged
	//	*BridgeEvent_TokenRotationRequested
	//	*BridgeEvent_CertRenewal
	//	*BridgeEvent_Unknown
	Event         isBridgeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEvent) Reset() {
	*x = BridgeEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEvent) ProtoMessage() {}

func (x *BridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEvent.ProtoReflect.Descriptor instead.
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *BridgeEvent) GetEvent() isBridgeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BridgeEvent) GetUserBanned() *UserBannedEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_UserBanned); ok {
			return x.UserBanned
		}
	}
	return nil
}

func (x *BridgeEvent) GetUserUnbanned() *UserUnbannedEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_UserUnbanned); ok {
			return x.UserUnbanned
		}
	}
	return nil
}

func (x *BridgeEvent) GetConnectionModeChanged() *ConnectionModeChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_ConnectionModeChanged); ok {
			return x.ConnectionModeChanged
		}
	}
	return nil
}

func (x *BridgeEvent) GetTokenRotationRequested() *TokenRotationRequestedEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_TokenRotationRequested); ok {
			return x.TokenRotationRequested
		}
	}
	return nil
}

func (x *BridgeEvent) GetCertRenewal() *CertRenewalEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_CertRenewal); ok {
			return x.CertRenewal
		}
	}
	return nil
}

func (x *BridgeEvent) GetUnknown() *UnknownEvent {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_Unknown); ok {
			return x.Unknown
		}
	}
	return nil
}

type isBridgeEvent_Event interface {
	isBridgeEvent_Event()
}

type BridgeEvent_UserBanned struct {
	UserBanned *UserBannedEvent `protobuf:"bytes,1,opt,name=user_banned,json=userBanned,proto3,oneof"`
}

type BridgeEvent_UserUnbanned struct {
	UserUnbanned *UserUnbannedEvent `protobuf:"bytes,2,opt,name=user_unbanned,json=userUnbanned,proto3,oneof"`
}

type BridgeEvent_ConnectionModeChanged struct {
	ConnectionModeChanged *ConnectionModeChangedEvent `protobuf:"bytes,3,opt,name=connection_mode_changed,json=connectionModeChanged,proto3,oneof"`
}

type BridgeEvent_TokenRotationRequested struct {
	TokenRotationRequested *TokenRotationRequestedEvent `protobuf:"bytes,4,opt,name=token_rotation_requested,json=tokenRotationRequested,proto3,oneof"`
}

type BridgeEvent_CertRenewal struct {
	CertRenewal *CertRenewalEvent `protobuf:"bytes,5,opt,name=cert_renewal,json=certRenewal,proto3,oneof"`
}

type BridgeEvent_Unknown struct {
	// Generic fallback for forward-compatible events the receiver doesn't know yet.
	// The receiver logs the event_type and ignores the payload.
	Unknown *UnknownEvent `protobuf:"bytes,15,opt,name=unknown,proto3,oneof"`
}

func (*BridgeEvent_UserBanned) isBridgeEvent_Event() {}

func (*BridgeEvent_UserUnbanned) isBridgeEvent_Event() {}

func (*BridgeEvent_ConnectionModeChanged) isBridgeEvent_Event() {}

func (*BridgeEvent_TokenRotationRequested) isBridgeEvent_Event() {}

func (*BridgeEvent_CertRenewal) isBridgeEvent_Event() {}

func (*BridgeEvent_Unknown) isBridgeEvent_Event() {}

type UserBannedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBannedEvent) Reset() {
	*x = UserBannedEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBannedEvent) ProtoMessage() {}

func (x *UserBannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBannedEvent.ProtoReflect.Descriptor instead.
func (*UserBannedEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *UserBannedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserUnbannedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnbannedEvent) Reset() {
	*x = UserUnbannedEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnbannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnbannedEvent) ProtoMessage() {}

func (x *UserUnbannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnbannedEvent.ProtoReflect.Descriptor instead.
func (*UserUnbannedEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *UserUnbannedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConnectionModeChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionModeChangedEvent) Reset() {
	*x = ConnectionModeChangedEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionModeChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionModeChangedEvent) ProtoMessage() {}

func (x *ConnectionModeChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionModeChangedEvent.ProtoReflect.Descriptor instead.
func (*ConnectionModeChangedEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionModeChangedEvent) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// UnknownEvent is a forward-compatibility fallback for events added after a receiver's build.
type UnknownEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownEvent) Reset() {
	*x = UnknownEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownEvent) ProtoMessage() {}

func (x *UnknownEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownEvent.ProtoReflect.Descriptor instead.
func (*UnknownEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *UnknownEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UnknownEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *Ping) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *Pong) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// HttpRequest represents an HTTP request to be executed by the Workspace locally.
type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery      string                 `protobuf:"bytes,4,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse is the Workspace's response after executing the HTTP request.
type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// DispatchRequest wraps an HttpRequest for stream-based dispatch.
type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *HttpRequest           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *DispatchRequest) GetRequest() *HttpRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// HeartbeatRequest is sent by the Workspace to report its status.
type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceUrl     string                 `protobuf:"bytes,1,opt,name=workspace_url,json=workspaceUrl,proto3" json:"workspace_url,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ConnectedClients int32                  `protobuf:"varint,4,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	ConnectivityMode string                 `protobuf:"bytes,5,opt,name=connectivity_mode,json=connectivityMode,proto3" json:"connectivity_mode,omitempty"`
	PublicPort       int32                  `protobuf:"varint,6,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	PublicUrl        string                 `protobuf:"bytes,7,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	// sfu_status reports the workspace's SFU reachability: "ok", "fail", "skipped", "not_configured".
	SfuStatus string `protobuf:"bytes,8,opt,name=sfu_status,json=sfuStatus,proto3" json:"sfu_status,omitempty"`
	// Address registry fields — explicit internal/external separation.
	InternalUrl   string `protobuf:"bytes,9,opt,name=internal_url,json=internalUrl,proto3" json:"internal_url,omitempty"`
	ExternalUrl   string `protobuf:"bytes,10,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	ExternalIp    string `protobuf:"bytes,11,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetWorkspaceUrl() string {
	if x != nil {
		return x.WorkspaceUrl
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *HeartbeatRequest) GetConnectivityMode() string {
	if x != nil {
		return x.ConnectivityMode
	}
	return ""
}

func (x *HeartbeatRequest) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *HeartbeatRequest) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *HeartbeatRequest) GetSfuStatus() string {
	if x != nil {
		return x.SfuStatus
	}
	return ""
}

func (x *HeartbeatRequest) GetInternalUrl() string {
	if x != nil {
		return x.InternalUrl
	}
	return ""
}

func (x *HeartbeatRequest) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *HeartbeatRequest) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

// HeartbeatResponse is returned by the Zentrale with operational parameters.
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ZentraleUrl     string                 `protobuf:"bytes,2,opt,name=zentrale_url,json=zentraleUrl,proto3" json:"zentrale_url,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	// expected_connectivity_mode is the connectivity tier the zentrale has
	// configured for this workspace. If non-empty and different from what the
	// workspace reported, the workspace should update its local DB to match.
	// This provides self-healing sync: even if a bridge event was lost, the
	// workspace will converge within one heartbeat cycle (~30s).
	ExpectedConnectivityMode string `protobuf:"bytes,5,opt,name=expected_connectivity_mode,json=expectedConnectivityMode,proto3" json:"expected_connectivity_mode,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetZentraleUrl() string {
	if x != nil {
		return x.ZentraleUrl
	}
	return ""
}

func (x *HeartbeatResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatResponse) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetExpectedConnectivityMode() string {
	if x != nil {
		return x.ExpectedConnectivityMode
	}
	return ""
}

// TokenRotationRequestedEvent is sent by the Zentrale to initiate token rotation.
// The Workspace applies the new token and responds with TokenRotationAck.
type TokenRotationRequestedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewToken       string                 `protobuf:"bytes,1,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
	OverlapSeconds int32                  `protobuf:"varint,2,opt,name=overlap_seconds,json=overlapSeconds,proto3" json:"overlap_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenRotationRequestedEvent) Reset() {
	*x = TokenRotationRequestedEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRotationRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRotationRequestedEvent) ProtoMessage() {}

func (x *TokenRotationRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRotationRequestedEvent.ProtoReflect.Descriptor instead.
func (*TokenRotationRequestedEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{19}
}

func (x *TokenRotationRequestedEvent) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

func (x *TokenRotationRequestedEvent) GetOverlapSeconds() int32 {
	if x != nil {
		return x.OverlapSeconds
	}
	return 0
}

// TokenRotationAck confirms that the Workspace has applied the new token.
type TokenRotationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	OverlapSeconds int32                  `protobuf:"varint,2,opt,name=overlap_seconds,json=overlapSeconds,proto3" json:"overlap_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenRotationAck) Reset() {
	*x = TokenRotationAck{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRotationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRotationAck) ProtoMessage() {}

func (x *TokenRotationAck) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRotationAck.ProtoReflect.Descriptor instead.
func (*TokenRotationAck) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *TokenRotationAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TokenRotationAck) GetOverlapSeconds() int32 {
	if x != nil {
		return x.OverlapSeconds
	}
	return 0
}

// CertRenewalEvent is sent by the Zentrale when it detects the workspace's
// client cert is nearing expiry. Contains a fresh cert+key signed by the CA.
// The Workspace writes the new cert to disk and reconnects.
type CertRenewalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"` // new client certificate (PEM)
	KeyPem        string                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`    // new client private key (PEM)
	CaPem         string                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`       // CA cert (PEM, for verification — may be unchanged)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewalEvent) Reset() {
	*x = CertRenewalEvent{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewalEvent) ProtoMessage() {}

func (x *CertRenewalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewalEvent.ProtoReflect.Descriptor instead.
func (*CertRenewalEvent) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{21}
}

func (x *CertRenewalEvent) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertRenewalEvent) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *CertRenewalEvent) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

// CertRenewalAck confirms the Workspace has stored the new cert.
type CertRenewalAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewalAck) Reset() {
	*x = CertRenewalAck{}
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewalAck) ProtoMessage() {}

func (x *CertRenewalAck) ProtoReflect() protoreflect.Message {
	mi := &file_robcord_bridge_v1_bridge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewalAck.ProtoReflect.Descriptor instead.
func (*CertRenewalAck) Descriptor() ([]byte, []int) {
	return file_robcord_bridge_v1_bridge_proto_rawDescGZIP(), []int{22}
}

func (x *CertRenewalAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CertRenewalAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_robcord_bridge_v1_bridge_proto protoreflect.FileDescriptor

const file_robcord_bridge_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1erobcord/bridge/v1/bridge.proto\x12\x11robcord.bridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x05\n" +
	"\x12EventStreamRequest\x12M\n" +
	"\x10session_open_ack\x18\x01 \x01(\v2!.robcord.bridge.v1.SessionOpenAckH\x00R\x0esessionOpenAck\x12F\n" +
	"\rsession_frame\x18\x02 \x01(\v2\x1f.robcord.bridge.v1.SessionFrameH\x00R\fsessionFrame\x12F\n" +
	"\rsession_close\x18\x03 \x01(\v2\x1f.robcord.bridge.v1.SessionCloseH\x00R\fsessionClose\x12-\n" +
	"\x04pong\x18\n" +
	" \x01(\v2\x17.robcord.bridge.v1.PongH\x00R\x04pong\x12C\n" +
	"\theartbeat\x18\v \x01(\v2#.robcord.bridge.v1.HeartbeatRequestH\x00R\theartbeat\x12N\n" +
	"\x11dispatch_response\x18\f \x01(\v2\x1f.robcord.bridge.v1.HttpResponseH\x00R\x10dispatchResponse\x12S\n" +
	"\x12token_rotation_ack\x18\r \x01(\v2#.robcord.bridge.v1.TokenRotationAckH\x00R\x10tokenRotationAck\x12M\n" +
	"\x10cert_renewal_ack\x18\x0e \x01(\v2!.robcord.bridge.v1.CertRenewalAckH\x00R\x0ecertRenewalAck\x12X\n" +
	"\x13workspace_broadcast\x18\x0f \x01(\v2%.robcord.bridge.v1.WorkspaceBroadcastH\x00R\x12workspaceBroadcastB\t\n" +
	"\apayload\"\x91\x04\n" +
	"\x13EventStreamResponse\x12C\n" +
	"\fsession_open\x18\x01 \x01(\v2\x1e.robcord.bridge.v1.SessionOpenH\x00R\vsessionOpen\x12F\n" +
	"\rsession_frame\x18\x02 \x01(\v2\x1f.robcord.bridge.v1.SessionFrameH\x00R\fsessionFrame\x12F\n" +
	"\rsession_close\x18\x03 \x01(\v2\x1f.robcord.bridge.v1.SessionCloseH\x00R\fsessionClose\x12C\n" +
	"\fbridge_event\x18\x05 \x01(\v2\x1e.robcord.bridge.v1.BridgeEventH\x00R\vbridgeEvent\x12-\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x17.robcord.bridge.v1.PingH\x00R\x04ping\x12O\n" +
	"\x10dispatch_request\x18\v \x01(\v2\".robcord.bridge.v1.DispatchRequestH\x00R\x0fdispatchRequest\x12U\n" +
	"\x12heartbeat_response\x18\f \x01(\v2$.robcord.bridge.v1.HeartbeatResponseH\x00R\x11heartbeatResponseB\t\n" +
	"\apayload\"a\n" +
	"\vSessionOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"_\n" +
	"\x0eSessionOpenAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Z\n" +
	"\fSessionFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_text\x18\x03 \x01(\bR\x06isText\"Y\n" +
	"\fSessionClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"A\n" +
	"\x12WorkspaceBroadcast\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\ais_text\x18\x02 \x01(\bR\x06isText\"\x86\x04\n" +
	"\vBridgeEvent\x12E\n" +
	"\vuser_banned\x18\x01 \x01(\v2\".robcord.bridge.v1.UserBannedEventH\x00R\n" +
	"userBanned\x12K\n" +
	"\ruser_unbanned\x18\x02 \x01(\v2$.robcord.bridge.v1.UserUnbannedEventH\x00R\fuserUnbanned\x12g\n" +
	"\x17connection_mode_changed\x18\x03 \x01(\v2-.robcord.bridge.v1.ConnectionModeChangedEventH\x00R\x15connectionModeChanged\x12j\n" +
	"\x18token_rotation_requested\x18\x04 \x01(\v2..robcord.bridge.v1.TokenRotationRequestedEventH\x00R\x16tokenRotationRequested\x12H\n" +
	"\fcert_renewal\x18\x05 \x01(\v2#.robcord.bridge.v1.CertRenewalEventH\x00R\vcertRenewal\x12;\n" +
	"\aunknown\x18\x0f \x01(\v2\x1f.robcord.bridge.v1.UnknownEventH\x00R\aunknownB\a\n" +
	"\x05event\"*\n" +
	"\x0fUserBannedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x11UserUnbannedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x1aConnectionModeChangedEvent\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"G\n" +
	"\fUnknownEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\";\n" +
	"\x04Ping\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\";\n" +
	"\x04Pong\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x8c\x02\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x04 \x01(\tR\brawQuery\x12E\n" +
	"\aheaders\x18\x05 \x03(\v2+.robcord.bridge.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.robcord.bridge.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x0fDispatchRequest\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.robcord.bridge.v1.HttpRequestR\arequest\"\x98\x03\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rworkspace_url\x18\x01 \x01(\tR\fworkspaceUrl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12+\n" +
	"\x11connected_clients\x18\x04 \x01(\x05R\x10connectedClients\x12+\n" +
	"\x11connectivity_mode\x18\x05 \x01(\tR\x10connectivityMode\x12\x1f\n" +
	"\vpublic_port\x18\x06 \x01(\x05R\n" +
	"publicPort\x12\x1d\n" +
	"\n" +
	"public_url\x18\a \x01(\tR\tpublicUrl\x12\x1d\n" +
	"\n" +
	"sfu_status\x18\b \x01(\tR\tsfuStatus\x12!\n" +
	"\finternal_url\x18\t \x01(\tR\vinternalUrl\x12!\n" +
	"\fexternal_url\x18\n" +
	" \x01(\tR\vexternalUrl\x12\x1f\n" +
	"\vexternal_ip\x18\v \x01(\tR\n" +
	"externalIp\"\xc9\x01\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fzentrale_url\x18\x02 \x01(\tR\vzentraleUrl\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12<\n" +
	"\x1aexpected_connectivity_mode\x18\x05 \x01(\tR\x18expectedConnectivityMode\"c\n" +
	"\x1bTokenRotationRequestedEvent\x12\x1b\n" +
	"\tnew_token\x18\x01 \x01(\tR\bnewToken\x12'\n" +
	"\x0foverlap_seconds\x18\x02 \x01(\x05R\x0eoverlapSeconds\"K\n" +
	"\x10TokenRotationAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0foverlap_seconds\x18\x02 \x01(\x05R\x0eoverlapSeconds\"]\n" +
	"\x10CertRenewalEvent\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\tR\x06keyPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\tR\x05caPem\"6\n" +
	"\x0eCertRenewalAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd0\x01\n" +
	"\x14WorkspaceLinkService\x12`\n" +
	"\vEventStream\x12%.robcord.bridge.v1.EventStreamRequest\x1a&.robcord.bridge.v1.EventStreamResponse(\x010\x01\x12V\n" +
	"\tHeartbeat\x12#.robcord.bridge.v1.HeartbeatRequest\x1a$.robcord.bridge.v1.HeartbeatResponseB3Z1github.com/NurRobin/robcord-common/proto/bridgev1b\x06proto3"

var (
	file_robcord_bridge_v1_bridge_proto_rawDescOnce sync.Once
	file_robcord_bridge_v1_bridge_proto_rawDescData []byte
)

func file_robcord_bridge_v1_bridge_proto_rawDescGZIP() []byte {
	file_robcord_bridge_v1_bridge_proto_rawDescOnce.Do(func() {
		file_robcord_bridge_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robcord_bridge_v1_bridge_proto_rawDesc), len(file_robcord_bridge_v1_bridge_proto_rawDesc)))
	})
	return file_robcord_bridge_v1_bridge_proto_rawDescData
}

var file_robcord_bridge_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_robcord_bridge_v1_bridge_proto_goTypes = []any{
	(*EventStreamRequest)(nil),          // 0: robcord.bridge.v1.EventStreamRequest
	(*EventStreamResponse)(nil),         // 1: robcord.bridge.v1.EventStreamResponse
	(*SessionOpen)(nil),                 // 2: robcord.bridge.v1.SessionOpen
	(*SessionOpenAck)(nil),              // 3: robcord.bridge.v1.SessionOpenAck
	(*SessionFrame)(nil),                // 4: robcord.bridge.v1.SessionFrame
	(*SessionClose)(nil),                // 5: robcord.bridge.v1.SessionClose
	(*WorkspaceBroadcast)(nil),          // 6: robcord.bridge.v1.WorkspaceBroadcast
	(*BridgeEvent)(nil),                 // 7: robcord.bridge.v1.BridgeEvent
	(*UserBannedEvent)(nil),             // 8: robcord.bridge.v1.UserBannedEvent
	(*UserUnbannedEvent)(nil),           // 9: robcord.bridge.v1.UserUnbannedEvent
	(*ConnectionModeChangedEvent)(nil),  // 10: robcord.bridge.v1.ConnectionModeChangedEvent
	(*UnknownEvent)(nil),                // 11: robcord.bridge.v1.UnknownEvent
	(*Ping)(nil),                        // 12: robcord.bridge.v1.Ping
	(*Pong)(nil),                        // 13: robcord.bridge.v1.Pong
	(*HttpRequest)(nil),                 // 14: robcord.bridge.v1.HttpRequest
	(*HttpResponse)(nil),                // 15: robcord.bridge.v1.HttpResponse
	(*DispatchRequest)(nil),             // 16: robcord.bridge.v1.DispatchRequest
	(*HeartbeatRequest)(nil),            // 17: robcord.bridge.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 18: robcord.bridge.v1.HeartbeatResponse
	(*TokenRotationRequestedEvent)(nil), // 19: robcord.bridge.v1.TokenRotationRequestedEvent
	(*TokenRotationAck)(nil),            // 20: robcord.bridge.v1.TokenRotationAck
	(*CertRenewalEvent)(nil),            // 21: robcord.bridge.v1.CertRenewalEvent
	(*CertRenewalAck)(nil),              // 22: robcord.bridge.v1.CertRenewalAck
	nil,                                 // 23: robcord.bridge.v1.HttpRequest.HeadersEntry
	nil,                                 // 24: robcord.bridge.v1.HttpResponse.HeadersEntry
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
}
var file_robcord_bridge_v1_bridge_proto_depIdxs = []int32{
	3,  // 0: robcord.bridge.v1.EventStreamRequest.session_open_ack:type_name -> robcord.bridge.v1.SessionOpenAck
	4,  // 1: robcord.bridge.v1.EventStreamRequest.session_frame:type_name -> robcord.bridge.v1.SessionFrame
	5,  // 2: robcord.bridge.v1.EventStreamRequest.session_close:type_name -> robcord.bridge.v1.SessionClose
	13, // 3: robcord.bridge.v1.EventStreamRequest.pong:type_name -> robcord.bridge.v1.Pong
	17, // 4: robcord.bridge.v1.EventStreamRequest.heartbeat:type_name -> robcord.bridge.v1.HeartbeatRequest
	15, // 5: robcord.bridge.v1.EventStreamRequest.dispatch_response:type_name -> robcord.bridge.v1.HttpResponse
	20, // 6: robcord.bridge.v1.EventStreamRequest.token_rotation_ack:type_name -> robcord.bridge.v1.TokenRotationAck
	22, // 7: robcord.bridge.v1.EventStreamRequest.cert_renewal_ack:type_name -> robcord.bridge.v1.CertRenewalAck
	6,  // 8: robcord.bridge.v1.EventStreamRequest.workspace_broadcast:type_name -> robcord.bridge.v1.WorkspaceBroadcast
	2,  // 9: robcord.bridge.v1.EventStreamResponse.session_open:type_name -> robcord.bridge.v1.SessionOpen
	4,  // 10: robcord.bridge.v1.EventStreamResponse.session_frame:type_name -> robcord.bridge.v1.SessionFrame
	5,  // 11: robcord.bridge.v1.EventStreamResponse.session_close:type_name -> robcord.bridge.v1.SessionClose
	7,  // 12: robcord.bridge.v1.EventStreamResponse.bridge_event:type_name -> robcord.bridge.v1.BridgeEvent
	12, // 13: robcord.bridge.v1.EventStreamResponse.ping:type_name -> robcord.bridge.v1.Ping
	16, // 14: robcord.bridge.v1.EventStreamResponse.dispatch_request:type_name -> robcord.bridge.v1.DispatchRequest
	18, // 15: robcord.bridge.v1.EventStreamResponse.heartbeat_response:type_name -> robcord.bridge.v1.HeartbeatResponse
	8,  // 16: robcord.bridge.v1.BridgeEvent.user_banned:type_name -> robcord.bridge.v1.UserBannedEvent
	9,  // 17: robcord.bridge.v1.BridgeEvent.user_unbanned:type_name -> robcord.bridge.v1.UserUnbannedEvent
	10, // 18: robcord.bridge.v1.BridgeEvent.connection_mode_changed:type_name -> robcord.bridge.v1.ConnectionModeChangedEvent
	19, // 19: robcord.bridge.v1.BridgeEvent.token_rotation_requested:type_name -> robcord.bridge.v1.TokenRotationRequestedEvent
	21, // 20: robcord.bridge.v1.BridgeEvent.cert_renewal:type_name -> robcord.bridge.v1.CertRenewalEvent
	11, // 21: robcord.bridge.v1.BridgeEvent.unknown:type_name -> robcord.bridge.v1.UnknownEvent
	25, // 22: robcord.bridge.v1.Ping.sent_at:type_name -> google.protobuf.Timestamp
	25, // 23: robcord.bridge.v1.Pong.sent_at:type_name -> google.protobuf.Timestamp
	23, // 24: robcord.bridge.v1.HttpRequest.headers:type_name -> robcord.bridge.v1.HttpRequest.HeadersEntry
	24, // 25: robcord.bridge.v1.HttpResponse.headers:type_name -> robcord.bridge.v1.HttpResponse.HeadersEntry
	14, // 26: robcord.bridge.v1.DispatchRequest.request:type_name -> robcord.bridge.v1.HttpRequest
	0,  // 27: robcord.bridge.v1.WorkspaceLinkService.EventStream:input_type -> robcord.bridge.v1.EventStreamRequest
	17, // 28: robcord.bridge.v1.WorkspaceLinkService.Heartbeat:input_type -> robcord.bridge.v1.HeartbeatRequest
	1,  // 29: robcord.bridge.v1.WorkspaceLinkService.EventStream:output_type -> robcord.bridge.v1.EventStreamResponse
	18, // 30: robcord.bridge.v1.WorkspaceLinkService.Heartbeat:output_type -> robcord.bridge.v1.HeartbeatResponse
	29, // [29:31] is the sub-list for method output_type
	27, // [27:29] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_robcord_bridge_v1_bridge_proto_init() }
func file_robcord_bridge_v1_bridge_proto_init() {
	if File_robcord_bridge_v1_bridge_proto != nil {
		return
	}
	file_robcord_bridge_v1_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*EventStreamRequest_SessionOpenAck)(nil),
		(*EventStreamRequest_SessionFrame)(nil),
		(*EventStreamRequest_SessionClose)(nil),
		(*EventStreamRequest_Pong)(nil),
		(*EventStreamRequest_Heartbeat)(nil),
		(*EventStreamRequest_DispatchResponse)(nil),
		(*EventStreamRequest_TokenRotationAck)(nil),
		(*EventStreamRequest_CertRenewalAck)(nil),
		(*EventStreamRequest_WorkspaceBroadcast)(nil),
	}
	file_robcord_bridge_v1_bridge_proto_msgTypes[1].OneofWrappers = []any{
		(*EventStreamResponse_SessionOpen)(nil),
		(*EventStreamResponse_SessionFrame)(nil),
		(*EventStreamResponse_SessionClose)(nil),
		(*EventStreamResponse_BridgeEvent)(nil),
		(*EventStreamResponse_Ping)(nil),
		(*EventStreamResponse_DispatchRequest)(nil),
		(*EventStreamResponse_HeartbeatResponse)(nil),
	}
	file_robcord_bridge_v1_bridge_proto_msgTypes[7].OneofWrappers = []any{
		(*BridgeEvent_UserBanned)(nil),
		(*BridgeEvent_UserUnbanned)(nil),
		(*BridgeEvent_ConnectionModeChanged)(nil),
		(*BridgeEvent_TokenRotationRequested)(nil),
		(*BridgeEvent_CertRenewal)(nil),
		(*BridgeEvent_Unknown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robcord_bridge_v1_bridge_proto_rawDesc), len(file_robcord_bridge_v1_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robcord_bridge_v1_bridge_proto_goTypes,
		DependencyIndexes: file_robcord_bridge_v1_bridge_proto_depIdxs,
		MessageInfos:      file_robcord_bridge_v1_bridge_proto_msgTypes,
	}.Build()
	File_robcord_bridge_v1_bridge_proto = out.File
	file_robcord_bridge_v1_bridge_proto_goTypes = nil
	file_robcord_bridge_v1_bridge_proto_depIdxs = nil
}
