// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: robcord/bridge/v1/bridge.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceLinkService_EventStream_FullMethodName = "/robcord.bridge.v1.WorkspaceLinkService/EventStream"
	WorkspaceLinkService_Heartbeat_FullMethodName   = "/robcord.bridge.v1.WorkspaceLinkService/Heartbeat"
)

// WorkspaceLinkServiceClient is the client API for WorkspaceLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspaceLink is the single service replacing WS Bridge + Reverse Channel + Heartbeat.
// The Workspace initiates all connections (outbound-only, NAT/CGNAT safe).
type WorkspaceLinkServiceClient interface {
	// EventStream: persistent bidirectional stream replacing WS Bridge.
	// Workspace opens on startup, reconnects on failure.
	// Multiplexes: session management, frame forwarding, bridge events, heartbeat, dispatch.
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventStreamRequest, EventStreamResponse], error)
	// Heartbeat: unary RPC replacing POST /api/heartbeat.
	// Workspace calls periodically to report status.
	// Can also be sent inline on the EventStream.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type workspaceLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceLinkServiceClient(cc grpc.ClientConnInterface) WorkspaceLinkServiceClient {
	return &workspaceLinkServiceClient{cc}
}

func (c *workspaceLinkServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventStreamRequest, EventStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceLinkService_ServiceDesc.Streams[0], WorkspaceLinkService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamRequest, EventStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceLinkService_EventStreamClient = grpc.BidiStreamingClient[EventStreamRequest, EventStreamResponse]

func (c *workspaceLinkServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkspaceLinkService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceLinkServiceServer is the server API for WorkspaceLinkService service.
// All implementations must embed UnimplementedWorkspaceLinkServiceServer
// for forward compatibility.
//
// WorkspaceLink is the single service replacing WS Bridge + Reverse Channel + Heartbeat.
// The Workspace initiates all connections (outbound-only, NAT/CGNAT safe).
type WorkspaceLinkServiceServer interface {
	// EventStream: persistent bidirectional stream replacing WS Bridge.
	// Workspace opens on startup, reconnects on failure.
	// Multiplexes: session management, frame forwarding, bridge events, heartbeat, dispatch.
	EventStream(grpc.BidiStreamingServer[EventStreamRequest, EventStreamResponse]) error
	// Heartbeat: unary RPC replacing POST /api/heartbeat.
	// Workspace calls periodically to report status.
	// Can also be sent inline on the EventStream.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedWorkspaceLinkServiceServer()
}

// UnimplementedWorkspaceLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceLinkServiceServer struct{}

func (UnimplementedWorkspaceLinkServiceServer) EventStream(grpc.BidiStreamingServer[EventStreamRequest, EventStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedWorkspaceLinkServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkspaceLinkServiceServer) mustEmbedUnimplementedWorkspaceLinkServiceServer() {}
func (UnimplementedWorkspaceLinkServiceServer) testEmbeddedByValue()                              {}

// UnsafeWorkspaceLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceLinkServiceServer will
// result in compilation errors.
type UnsafeWorkspaceLinkServiceServer interface {
	mustEmbedUnimplementedWorkspaceLinkServiceServer()
}

func RegisterWorkspaceLinkServiceServer(s grpc.ServiceRegistrar, srv WorkspaceLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceLinkService_ServiceDesc, srv)
}

func _WorkspaceLinkService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkspaceLinkServiceServer).EventStream(&grpc.GenericServerStream[EventStreamRequest, EventStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceLinkService_EventStreamServer = grpc.BidiStreamingServer[EventStreamRequest, EventStreamResponse]

func _WorkspaceLinkService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceLinkServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceLinkService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceLinkServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceLinkService_ServiceDesc is the grpc.ServiceDesc for WorkspaceLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robcord.bridge.v1.WorkspaceLinkService",
	HandlerType: (*WorkspaceLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _WorkspaceLinkService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _WorkspaceLinkService_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "robcord/bridge/v1/bridge.proto",
}
